const express=require('express')
const router=express.Router()
const Course = require ('../controllers/courseController.js')
const Trainee = require('../controllers/TraineeController')
const Mid = require('../middleware/CheckLogin')

const CheckLogin = require('../middleware/CheckLogin')

router.use(CheckLogin.IndLogin)
router.get('/viewAllCourses',Course.viewCourses)
router.put('/filterCoursesSR',Course.filterSubjectRating)
router.put('/filterCoursesP',Course.filterPrice)
router.post('/Search',Course.Search)
router.put('/viewDetails',Course.viewAllDetails)
router.post('/rateInstructor',Trainee.rateInstructor)
router.post('/rateCourse',Trainee.rateCourse)
router.post('/changePassword',Trainee.changePassworddInd)
router.post('/addItrainee',Trainee.addItrainee)
router.post('/signUp',Trainee.signUpI)
router.post('/login',Trainee.loginI)
router.post('/logout',Trainee.logout)
router.get('/Account',Trainee.fetchIndAccount)
router.get('/viewSubtitles',Course.viewSubtitles)
router.get('/subVideo',Course.viewSubtitlesVid)
router.post('/forgotPass',Trainee.forgotPassword)
router.get('/reset-password/:id/:token',Trainee.resetPass)
router.post('/reset-password/:id/:token',Trainee.resetPassw)
router.get('/exercises',Course.viewExercises)
router.get('/correctAnswer',Course.getCorrectAnswers)
router.get('/getProg',Trainee.getProgression)
router.post('/grade',Course.getGrade)
router.get('/getQuestions',Course.viewQuestions)
router.post('/regCourse',Trainee.regCourse)
router.post('/setGrade',Trainee.quizGrade)
router.post('/startQuiz',Trainee.startQuiz)
router.post('/acceptPolicy',Course.acceptPolicy)
router.get('/getMyCoursesDetails',Trainee.IndCourses)
router.post('/reportCourse',Course.INreportCourse)
router.get('/myPrevReports',Trainee.IndViewMyReports)
router.get('/getMyCourses',Trainee.indViewMyCourses)
router.post('/buyCourse',Trainee.buyCourse)



module.exports = router